import {
  Controller,
  Get,
  Post,
  Body,
  Patch,
  Param,
  Delete,
  UseGuards,
} from '@nestjs/common';

import { Roles } from '../common/decorators/roles.decorator';
import { JwtAuthGuard } from '../common/guards/jwt-auth.guard';
import { RolesGuard } from '../common/guards/roles.guard';
import { PickupsService } from './pickups.service';
import { CreatePickupDto } from './dto/create-pickup.dto';
import { UpdatePickupDto } from './dto/update-pickup.dto';

/**
 * Pickups was generated by `nest g resource` and kept its scaffolded
 * controller: no guards at all, while PickupsModule is registered in
 * AppModule and the service reads and writes a real table. That left
 * GET/POST/PATCH/DELETE /pickups reachable by anyone on the internet —
 * confirmed against production, where the routes are served (they only
 * failed at the database layer, not at authentication).
 *
 * Every other controller in this API is guarded by JwtAuthGuard + RolesGuard;
 * this brings pickups in line with that. Read is available to any
 * authenticated role (a driver needs to see their own pickups); mutations
 * require admin or manager, matching how the other operational resources
 * are scoped.
 */
@Controller('pickups')
@UseGuards(JwtAuthGuard, RolesGuard)
export class PickupsController {
  constructor(private readonly pickupsService: PickupsService) {}

  @Post()
  @Roles('admin', 'manager')
  create(@Body() createPickupDto: CreatePickupDto) {
    return this.pickupsService.create(createPickupDto);
  }

  @Get()
  @Roles('admin', 'manager', 'staff', 'driver')
  findAll() {
    return this.pickupsService.findAll();
  }

  @Get(':id')
  @Roles('admin', 'manager', 'staff', 'driver')
  findOne(@Param('id') id: string) {
    return this.pickupsService.findOne(+id);
  }

  @Patch(':id')
  @Roles('admin', 'manager')
  update(@Param('id') id: string, @Body() updatePickupDto: UpdatePickupDto) {
    return this.pickupsService.update(+id, updatePickupDto);
  }

  @Delete(':id')
  @Roles('admin', 'manager')
  remove(@Param('id') id: string) {
    return this.pickupsService.remove(+id);
  }
}
