FROM node:22-alpine AS builder

WORKDIR /usr/src/app

COPY package*.json vite.config.js index.html ./
RUN npm ci

COPY src/ ./src/
RUN npm run build

FROM nginx:alpine AS runner

COPY --from=builder /usr/src/app/dist /usr/share/nginx/html
COPY ../../infrastructure/nginx/nginx-local.conf /etc/nginx/conf.d/default.conf

EXPOSE 80 5173

CMD ["nginx", "-g", "daemon off;"]
